export const CREDIT_ACTION_CODES = {
  INVOICE_UPLOAD: "INVOICE_UPLOAD",
  VENDOR_UPLOAD: "VENDOR_UPLOAD",
  INVOICE_MATCHING: "INVOICE_MATCHING",
  PO_UPLOAD: "PO_UPLOAD",
  GRN_UPLOAD: "GRN_UPLOAD",
  GST_VENDOR_DETAILS_API: "GST_VENDOR_DETAILS_API",
  GST_RETURN_PREFERENCE_API: "GST_RETURN_PREFERENCE_API",
  GST_RETURNS_API: "GST_RETURNS_API",
  GST_DOCUMENTS_API: "GST_DOCUMENTS_API",
  GST_LEDGER_API: "GST_LEDGER_API",
  GST_RECON_API: "GST_RECON_API",
  TDS_API: "TDS_API",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
};

export const CREDIT_INVALIDATION_TAGS = ["Credits"];
