export const CREDIT_ACTION_CODES = {
  INVOICE_UPLOAD: "INVOICE_UPLOAD",
  VENDOR_UPLOAD: "VENDOR_UPLOAD",
  INVOICE_MATCHING: "INVOICE_MATCHING",
  PO_UPLOAD: "PO_UPLOAD",
  GRN_UPLOAD: "GRN_UPLOAD",
  GST_INVOICE_API: "GST_INVOICE_API",
  GST_RECON_API: "GST_RECON_API",
  TDS_API: "TDS_API",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
};

export const CREDIT_INVALIDATION_TAGS = ["Credits"];
