export const PAYOUT_MODES = ["IMPS", "NEFT", "RTGS", "INEFT"];

export const PAYOUT_STATUS = {
  INITIATED: "INITIATED",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  RETURNED: "RETURNED",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
};

export const BENEFICIARY_STATUS = {
  ACTIVE: "ACTIVE",
  ACTIVATING: "ACTIVATING",
  FAILED: "FAILED",
};

export const CIB_STATE = {
  NOT_STARTED: "NOT_STARTED",
  PENDING_SELF_APPROVAL: "PENDING_SELF_APPROVAL",
  REGISTERED: "REGISTERED",
  FAILED: "FAILED",
};

export const ACCOUNT_LINK_STATUS = {
  LINKED: "LINKED",
  NOT_LINKED: "NOT_LINKED",
  ERROR: "ERROR",
};

export const GATE_STATE = {
  NOT_READY: "NOT_READY",
  ACCOUNT_PENDING: "ACCOUNT_PENDING",
  CIB_PENDING: "CIB_PENDING",
  BENEFICIARY_PENDING: "BENEFICIARY_PENDING",
  READY: "READY",
};

export const ACCOUNT_TYPES = [
  { value: "CURRENT", label: "Current" },
  { value: "ESCROW", label: "Escrow" },
];
