export const PAYOUT_MODES = ["IMPS", "NEFT", "RTGS", "INEFT"];

export const PAYOUT_STATUS = {
  INITIATED: "INITIATED",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  RETURNED: "RETURNED",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
};

export const BENEFICIARY_STATUS = {
  ACTIVE: "ACTIVE",
  ACTIVATING: "ACTIVATING",
  FAILED: "FAILED",
};

export const CIB_STATE = {
  NOT_STARTED: "NOT_STARTED",
  PENDING_SELF_APPROVAL: "PENDING_SELF_APPROVAL",
  REGISTERED: "REGISTERED",
  FAILED: "FAILED",
};

export const ACCOUNT_LINK_STATUS = {
  LINKED: "LINKED",
  NOT_LINKED: "NOT_LINKED",
  ERROR: "ERROR",
};

export const BANK_ACCOUNT_VERIFICATION_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const BANKING_SETUP_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  ACTION_REQUIRED: "ACTION_REQUIRED",
  CONFIGURED: "CONFIGURED",
};

export const BANK_LINK_OPTIONS = [
  {
    value: "IDFC",
    label: "IDFC Bank",
    shortLabel: "IDFC",
    ifscPrefix: "IDFB",
  },
];

export const GATE_STATE = {
  NOT_READY: "NOT_READY",
  ACCOUNT_PENDING: "ACCOUNT_PENDING",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  ACTION_REQUIRED: "ACTION_REQUIRED",
  CONFIGURED: "CONFIGURED",
  CIB_PENDING: "CIB_PENDING",
  BENEFICIARY_PENDING: "BENEFICIARY_PENDING",
  READY: "READY",
};

export const ACCOUNT_TYPES = [
  { value: "CURRENT", label: "Current" },
  { value: "ESCROW", label: "Escrow" },
];
